
service:
  image: ongo360/omega-demo-service:0.1
  command: java -jar /opt/omega-demo/omega-demo-service-0.1.jar
  restart: always
  ports:
   - 8080
  environment:
   - spring.application.name=omega-demo-service
   - spring.cloud.config.profile=dev
   - spring.cloud.config.label=master
   - spring.cloud.config.discovery.enabled=true
   - spring.cloud.config.discovery.serviceId=omega-framework-configserver
   - eureka.client.serviceUrl.defaultZone=http://eureka:8080/eureka/

portal:
  image: ongo360/omega-demo-portal:0.1
  command: java -jar /opt/omega-demo/omega-demo-portal-0.1.jar
  restart: always
  ports:
   - 8080
  environment:
   - spring.application.name=omega-demo-protal
   - spring.cloud.config.profile=dev
   - spring.cloud.config.label=master
   - spring.cloud.config.discovery.enabled=true
   - spring.cloud.config.discovery.serviceId=omega-framework-configserver
   - eureka.client.serviceUrl.defaultZone=http://eureka:8080/eureka/

